"""initial

Revision ID: 499cc7fc17a0
Revises: 
Create Date: 2024-05-23 15:43:32.840010

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '499cc7fc17a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_points',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('tg_user_id', sa.Integer(), nullable=False),
                    sa.Column('tg_chat_id', sa.Integer(), nullable=False),
                    sa.Column('tg_username', sa.String(), nullable=True),
                    sa.Column('phone', sa.String(), nullable=True),
                    sa.Column('concrete_discount', sa.Integer(), nullable=False, default=0),
                    sa.Column('delivery_discount', sa.Integer(), nullable=False, default=0),
                    sa.Column('dispatch_point_id', sa.Integer(), nullable=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('register_time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['dispatch_point_id'], ['dispatch_points.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('dispatch_points')
    # ### end Alembic commands ###
