"""add discounts for cashless payments

Revision ID: 7829c00ba71a
Revises: 7a3e9bc0a8ff
Create Date: 2024-06-06 12:55:55.737420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7829c00ba71a'
down_revision: Union[str, None] = '7a3e9bc0a8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_discounts', sa.Column('concrete_discount_vat', sa.Integer(), nullable=True))
    op.add_column('user_discounts', sa.Column('delivery_discount_vat', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_discounts', 'delivery_discount_vat')
    op.drop_column('user_discounts', 'concrete_discount_vat')
    # ### end Alembic commands ###
